select
         day as date,
         MAR188,
         MAR284,
         MAR285,
         MAR286,
         MAR287,
         MAR288,
         MAR289,
         MAR290,
         MAR291,
         MAR934,
         MAR935,
         MAR936,
         MAR274,
         MAR275,
         MAR276,
         MAR277,
         MAR278,
         MAR279,
         MAR280,
         MAR281,
         MAR282,
         MAR342,
         MAR343,
         MAR574,
         MAR575,
         MAR576,
         MAR580,
         MAR581,
         MAR582,
         MAR712,
         MAR928,
         MAR929,
         MAR930,
         MAR713,
         MAR1027,
         MAR1061,
		 MAR1062,
         MAR1063,
		 MAR1103,
         MAR1109,
		 MAR1117,
         MAR2229,
		 MAR1158,
         MAR1224,
         MAR1699,
         MAR1710,
         MAR1717,
         MAR1724,
         MAR1731,
         MAR1738,
         MAR1745,
         MAR1752,
         MAR1759,
         MAR1766,
         MAR1980,
         MAR1773,
         MAR1780,
         MAR1787,
         MAR1794,
         MAR1801,
         MAR1808,
         MAR1815,
         MAR1822,
         MAR1987,
		 MAR1994,
         MAR1829,
         MAR1836,
         MAR1843,
         MAR1850,
         MAR1857,
         MAR1864,
         MAR2001,
         MAR1871,
         MAR1878,
         MAR1883,
         MAR1888,
         MAR1893,
		 MAR1706,
         MAR1713,
         MAR1720,
         MAR1727,
         MAR1734,
         MAR1741,
         MAR1748,
         MAR1755,
         MAR1762,
         MAR1769,
         MAR1983,
         MAR1776,
         MAR1783,
         MAR1790,
         MAR1797,
         MAR1804,
         MAR1811,
         MAR1818,
         MAR1825,
         MAR1990,
         MAR1997,
         MAR1832,
         MAR1839,
         MAR1846,
         MAR1853,
         MAR1860,
         MAR1867,
         MAR2004,
         MAR1879,
		 MAR1884,
		 MAR1889,
		 MAR1894,
         MAR2211,
         MAR2212,
         MAR2213,
         MAR2214,
         MAR2215,
         MAR2221,
         coalesce(MAR188/nullif(yelp_non_positive_reviews,0),0) as MAR1874,
         coalesce(MAR188/nullif(all_reviews_yelp,0),0) as MAR292,
         coalesce(MAR284/nullif(all_reviews_yelp_paloalto,0),0) as MAR293,
         coalesce(MAR285/nullif(all_reviews_yelp_watsonville,0),0) as MAR294,
         coalesce(MAR286/nullif(all_reviews_yelp_sacramento,0),0) as MAR295,
         coalesce(MAR287/nullif(all_reviews_yelp_stockton,0),0) as MAR296,
         coalesce(MAR288/nullif(all_reviews_yelp_oakland,0),0) as MAR297,
         coalesce(MAR289/nullif(all_reviews_yelp_fresno,0),0) as MAR298,
         coalesce(MAR290/nullif(all_reviews_yelp_san_jose,0),0) as MAR299,
         coalesce(MAR291/nullif(all_reviews_yelp_napa,0),0) as MAR300,
         coalesce(MAR343/nullif(all_reviews_yelp_san_francisco,0),0) as MAR344,
         coalesce(MAR574/nullif(all_reviews_yelp_riverside,0),0) as MAR577,
         coalesce(MAR575/nullif(all_reviews_yelp_lake_forest,0),0) as MAR578,
         coalesce(MAR576/nullif(all_reviews_yelp_thousand_oaks,0),0) as MAR579,
         coalesce(MAR713/nullif(all_reviews_yelp_los_angeles,0),0) as MAR714,
         coalesce(MAR934/nullif(all_reviews_yelp_san_diego,0),0) as MAR931,
         coalesce(MAR935/nullif(all_reviews_yelp_dallas,0),0) as MAR932,
         coalesce(MAR936/nullif(all_reviews_yelp_fort_worth,0),0) as MAR933,
         coalesce(MAR1062/nullif(all_reviews_yelp_houston,0),0) as MAR1064,
         coalesce(MAR1109/nullif(all_reviews_yelp_san_antonio,0),0) as MAR1110,
         coalesce(MAR1103/nullif(all_reviews_yelp_austin,0),0) as MAR1104,
         coalesce(MAR1063/nullif(all_reviews_yelp_atlanta,0),0) as MAR1065,
         coalesce(MAR1117/nullif(all_reviews_yelp_baltimore,0),0) as MAR1118,
         coalesce(MAR1158/nullif(all_reviews_yelp_maryland_dc,0),0) as MAR1159,
         coalesce(MAR1224/nullif(all_reviews_yelp_philadelphia,0),0) as MAR1225,
         coalesce(MAR1503/nullif(all_reviews_yelp_arlington,0),0) as MAR1504,
         coalesce(MAR1613/nullif(all_reviews_yelp_miami,0),0) as MAR1614,
         coalesce(MAR1661/nullif(all_reviews_yelp_orlando,0),0) as MAR1662,
         coalesce(MAR2229/nullif(all_reviews_yelp_seattle,0),0) as MAR2230
         from
(
select
        *,
        rank() over (partition by day order by date desc) as rank
from
(
with calc_series as
(
    select
        generate_series('2018-04-15', current_date, '1 day')::date as day
),
positive_reviews as
(
	select
		fr.id as review_id,
		case when mnl.channel_id in (3,10) then row_number() over (partition by fr.order_id order by fr.posted_at) else 1 end as ha_review_rank
	from feedback_review fr
    left join marketing_localaccount mnl on mnl.id = fr.account_id
),
yelp_data as
(
    select
        (posted_at at time zone 'pst')::date as date_id,
        count(fr.id) filter (where fr.is_yelp_recommended is true) as yelp_positive_reviews,
        count(fr.id) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is false) as yelp_non_positive_reviews,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Palo Alto') as yelp_positive_reviews_palo_alto,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Jose') as yelp_positive_reviews_san_jose,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Oakland') as yelp_positive_reviews_oakland,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Francisco') as yelp_positive_reviews_san_francisco,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Sacramento') as yelp_positive_reviews_sacramento,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Napa') as yelp_positive_reviews_napa,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Watsonville') as yelp_positive_reviews_watsonville,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Fresno') as yelp_positive_reviews_fresno,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Stockton') as yelp_positive_reviews_stockton,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Riverside') as yelp_positive_reviews_riverside,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Lake Forest') as yelp_positive_reviews_lake_forest,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Thousand Oaks') as yelp_positive_reviews_thousand_oaks,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Los Angeles') as yelp_positive_reviews_los_angeles,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Diego') as yelp_positive_reviews_san_diego,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Dallas') as yelp_positive_reviews_dallas,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Fort Worth') as yelp_positive_reviews_fort_worth,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Houston') as yelp_positive_reviews_houston,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Antonio') as yelp_positive_reviews_san_antonio,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Austin') as yelp_positive_reviews_austin,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Atlanta') as yelp_positive_reviews_atlanta,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Baltimore') as yelp_positive_reviews_baltimore,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Maryland DC') as yelp_positive_reviews_maryland_dc,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Philadelphia') as yelp_positive_reviews_philadelphia,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Arlington') as yelp_positive_reviews_arlington,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Miami') as yelp_positive_reviews_miami,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Orlando') as yelp_positive_reviews_orlando,
        count(fr.id) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Seattle') as yelp_positive_reviews_seattle,
        --total_reviews
        count(fr.id) as all_reviews,
        count(fr.id) filter (where pcnm.market_id = 2) as all_reviews_cn_eb,
        count(fr.id) filter (where pcnm.market_id = 3) as all_reviews_cn_sa,
        count(fr.id) filter (where pcnm.market_id in (4,30,31)) as all_reviews_cn_sb,
        count(fr.id) filter (where pcnm.market_id = 30) as all_reviews_cn_sj,
        count(fr.id) filter (where pcnm.market_id = 31) as all_reviews_cn_pa,
        count(fr.id) filter (where pcnm.market_id = 9) as all_reviews_cn_nb,
        count(fr.id) filter (where pcnm.market_id = 8) as all_reviews_cn_sf,
        count(fr.id) filter (where pcnm.market_id = 10) as all_reviews_cn_fr,
        count(fr.id) filter (where pcnm.market_id = 29) as all_reviews_cn_st,
        count(fr.id) filter (where pcnm.market_id = 4) as all_reviews_cn_wa,
        count(fr.id) filter (where pcnm.market_id = 14) as all_reviews_cs_sv,
        count(fr.id) filter (where pcnm.market_id = 5) as all_reviews_cs_oc,
        count(fr.id) filter (where pcnm.market_id = 6) as all_reviews_cs_la,
        count(fr.id) filter (where pcnm.market_id = 7) as all_reviews_cs_vc,
        count(fr.id) filter (where pcnm.market_id = 1) as all_reviews_cs_sd,
        count(fr.id) filter (where pcnm.market_id = 16) as all_reviews_tx_dl,
        count(fr.id) filter (where pcnm.market_id = 16) as all_reviews_tx_sa,
        count(fr.id) filter (where pcnm.market_id = 17) as all_reviews_tx_fw,
        count(fr.id) filter (where pcnm.market_id = 18) as all_reviews_tx_ht,
        count(fr.id) filter (where pcnm.market_id = 32) as all_reviews_tx_au,
        count(fr.id) filter (where pcnm.market_id = 20) as all_reviews_ga_at,
        count(fr.id) filter (where pcnm.market_id = 22) as all_reviews_md_bl,
        count(fr.id) filter (where pcnm.market_id = 21) as all_reviews_md_dc,
        count(fr.id) filter (where pcnm.market_id = 33) as all_reviews_pa_ph,
        count(fr.id) filter (where pcnm.market_id = 35) as all_reviews_va_ar,
        count(fr.id) filter (where pcnm.market_id = 24) as all_reviews_fl_mi,
        count(fr.id) filter (where pcnm.market_id = 26) as all_reviews_fl_or,
        count(fr.id) filter (where mnl.channel_id = 1) as all_reviews_yelp,
        count(fr.id) filter (where mnl.channel_id = 1 and fr.score > 4) as all_positive_reviews_yelp,
        count(fr.id) filter (where mnl.channel_id = 2) as all_reviews_google,
        count(fr.id) filter (where mnl.channel_id = 2 and fr.score > 4) as all_positive_reviews_google,
        count(fr.id) filter (where mnl.channel_id in (3,10)) as all_reviews_ha,
        count(fr.id) filter (where mnl.channel_id in (3,10) and fr.score > 4) as all_positive_reviews_ha,
        count(fr.id) filter (where mnl.channel_id = 4) as all_reviews_tt,
        count(fr.id) filter (where mnl.channel_id = 4 and fr.score > 4) as all_positive_reviews_tt,
        count(fr.id) filter (where mnl.channel_id = 5) as all_reviews_bbb,
        count(fr.id) filter (where mnl.channel_id = 5 and fr.score > 4) as all_positive_reviews_bbb,
        count(fr.id) filter (where mnl.label = 'Yelp - Palo Alto') as all_reviews_palo_alto,
        count(fr.id) filter (where mnl.label = 'Yelp - San Jose') as all_reviews_san_jose,
        count(fr.id) filter (where mnl.label = 'Yelp - Oakland') as all_reviews_oakland,
        count(fr.id) filter (where mnl.label = 'Yelp - San Francisco') as all_reviews_san_francisco,
        count(fr.id) filter (where mnl.label = 'Yelp - Sacramento') as all_reviews_sacramento,
        count(fr.id) filter (where mnl.label = 'Yelp - Napa') as all_reviews_napa,
        count(fr.id) filter (where mnl.label = 'Yelp - Watsonville') as all_reviews_watsonville,
        count(fr.id) filter (where mnl.label = 'Yelp - Fresno') as all_reviews_fresno,
        count(fr.id) filter (where mnl.label = 'Yelp - Stockton') as all_reviews_stockton,
        count(fr.id) filter (where mnl.label = 'Yelp - Riverside') as all_reviews_riverside,
        count(fr.id) filter (where mnl.label = 'Yelp - Lake Forest') as all_reviews_lake_forest,
        count(fr.id) filter (where mnl.label = 'Yelp - Thousand Oaks') as all_reviews_thousand_oaks,
        count(fr.id) filter (where mnl.label = 'Yelp - Los Angeles') as all_reviews_los_angeles,
        count(fr.id) filter (where mnl.label = 'Yelp - San Diego') as all_reviews_san_diego,
        count(fr.id) filter (where mnl.label = 'Yelp - Dallas') as all_reviews_dallas,
        count(fr.id) filter (where mnl.label = 'Yelp - Fort Worth') as all_reviews_fort_worth,
        count(fr.id) filter (where mnl.label = 'Yelp - Houston') as all_reviews_houston,
        count(fr.id) filter (where mnl.label = 'Yelp - San Antonio') as all_reviews_san_antonio,
        count(fr.id) filter (where mnl.label = 'Yelp - Austin') as all_reviews_austin,
        count(fr.id) filter (where mnl.label = 'Yelp - Atlanta') as all_reviews_atlanta,
        count(fr.id) filter (where mnl.label = 'Yelp - Baltimore') as all_reviews_baltimore,
        count(fr.id) filter (where mnl.label = 'Yelp - Maryland DC') as all_reviews_maryland_dc,
        count(fr.id) filter (where mnl.label = 'Yelp - Philadelphia') as all_reviews_philadelphia,
        count(fr.id) filter (where mnl.label = 'Yelp - Arlington') as all_reviews_arlington,
        count(fr.id) filter (where mnl.label = 'Yelp - Miami') as all_reviews_miami,
        count(fr.id) filter (where mnl.label = 'Yelp - Orlando') as all_reviews_orlando,
		--yelp_all_reviews
        count(fr.id) filter (where mnl.label = 'Yelp - Palo Alto') as all_reviews_yelp_palo_alto,
        count(fr.id) filter (where mnl.label = 'Yelp - San Jose') as all_reviews_yelp_san_jose,
        count(fr.id) filter (where mnl.label = 'Yelp - Oakland') as all_reviews_yelp_oakland,
        count(fr.id) filter (where mnl.label = 'Yelp - San Francisco') as all_reviews_yelp_san_francisco,
        count(fr.id) filter (where mnl.label = 'Yelp - Sacramento') as all_reviews_yelp_sacramento,
        count(fr.id) filter (where mnl.label = 'Yelp - Napa') as all_reviews_yelp_napa,
        count(fr.id) filter (where mnl.label = 'Yelp - Watsonville') as all_reviews_yelp_watsonville,
        count(fr.id) filter (where mnl.label = 'Yelp - Fresno') as all_reviews_yelp_fresno,
        count(fr.id) filter (where mnl.label = 'Yelp - Stockton') as all_reviews_yelp_stockton,
        count(fr.id) filter (where mnl.label = 'Yelp - Riverside') as all_reviews_yelp_riverside,
        count(fr.id) filter (where mnl.label = 'Yelp - Lake Forest') as all_reviews_yelp_lake_forest,
        count(fr.id) filter (where mnl.label = 'Yelp - Thousand Oaks') as all_reviews_yelp_thousand_oaks,
        count(fr.id) filter (where mnl.label = 'Yelp - Los Angeles') as all_reviews_yelp_los_angeles,
        count(fr.id) filter (where mnl.label = 'Yelp - San Diego') as all_reviews_yelp_san_diego,
        count(fr.id) filter (where mnl.label = 'Yelp - Dallas') as all_reviews_yelp_dallas,
        count(fr.id) filter (where mnl.label = 'Yelp - Fort Worth') as all_reviews_yelp_fort_worth,
        count(fr.id) filter (where mnl.label = 'Yelp - Houston') as all_reviews_yelp_houston,
        count(fr.id) filter (where mnl.label = 'Yelp - San Antonio') as all_reviews_yelp_san_antonio,
        count(fr.id) filter (where mnl.label = 'Yelp - Austin') as all_reviews_yelp_austin,
        count(fr.id) filter (where mnl.label = 'Yelp - Atlanta') as all_reviews_yelp_atlanta,
        count(fr.id) filter (where mnl.label = 'Yelp - Baltimore') as all_reviews_yelp_baltimore,
        count(fr.id) filter (where mnl.label = 'Yelp - Maryland DC') as all_reviews_yelp_maryland_dc,
        count(fr.id) filter (where mnl.label = 'Yelp - Philadelphia') as all_reviews_yelp_philadelphia,
        count(fr.id) filter (where mnl.label = 'Yelp - Arlington') as all_reviews_yelp_arlington,
        count(fr.id) filter (where mnl.label = 'Yelp - Miami') as all_reviews_yelp_miami,
        count(fr.id) filter (where mnl.label = 'Yelp - /orlando') as all_reviews_yelp_orlando,
        count(fr.id) filter (where mnl.label = 'Yelp - Seattle') as all_reviews_yelp_seattle,
        count(fr.id) filter (where mnl.label = '') as all_reviews_yelp_no_location,
        --avg_scores
        avg(fr.score) as avg_score,
        avg(fr.score) filter (where pcnm.market_id = 2) as avg_score_cn_eb,
        avg(fr.score) filter (where pcnm.market_id = 3) as avg_score_cn_sa,
        avg(fr.score) filter (where pcnm.market_id in (4,30,31)) as avg_score_cn_sb,
        avg(fr.score) filter (where pcnm.market_id = 30) as avg_score_cn_sj,
        avg(fr.score) filter (where pcnm.market_id = 31) as avg_score_cn_pa,
        avg(fr.score) filter (where pcnm.market_id = 9) as avg_score_cn_nb,
        avg(fr.score) filter (where pcnm.market_id = 8) as avg_score_cn_sf,
        avg(fr.score) filter (where pcnm.market_id = 10) as avg_score_cn_fr,
        avg(fr.score) filter (where pcnm.market_id = 29) as avg_score_cn_st,
        avg(fr.score) filter (where pcnm.market_id = 4) as avg_score_cn_wa,
        avg(fr.score) filter (where pcnm.market_id = 14) as avg_score_cs_sv,
        avg(fr.score) filter (where pcnm.market_id = 5) as avg_score_cs_oc,
        avg(fr.score) filter (where pcnm.market_id = 6) as avg_score_cs_la,
        avg(fr.score) filter (where pcnm.market_id = 7) as avg_score_cs_vc,
        avg(fr.score) filter (where pcnm.market_id = 1) as avg_score_cs_sd,
        avg(fr.score) filter (where pcnm.market_id = 16) as avg_score_tx_dl,
        avg(fr.score) filter (where pcnm.market_id = 19) as avg_score_tx_sa,
        avg(fr.score) filter (where pcnm.market_id = 17) as avg_score_tx_fw,
        avg(fr.score) filter (where pcnm.market_id = 18) as avg_score_tx_ht,
        avg(fr.score) filter (where pcnm.market_id = 32) as avg_score_tx_au,
        avg(fr.score) filter (where pcnm.market_id = 20) as avg_score_ga_at,
        avg(fr.score) filter (where pcnm.market_id = 22) as avg_score_md_bl,
        avg(fr.score) filter (where pcnm.market_id = 21) as avg_score_md_dc,
        avg(fr.score) filter (where pcnm.market_id = 33) as avg_score_pa_ph,
        avg(fr.score) filter (where pcnm.market_id = 35) as avg_score_va_ar,
        avg(fr.score) filter (where pcnm.market_id = 24) as avg_score_fl_mi,
        avg(fr.score) filter (where pcnm.market_id = 26) as avg_score_fl_or,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true) as yelp_avg_score,
        avg(fr.score) filter (where mnl.channel_id = 2) as google_avg_score,
        avg(fr.score) filter (where mnl.channel_id in (3,10)) as ha_avg_score,
        avg(fr.score) filter (where mnl.channel_id = 4) as tt_avg_score,
        avg(fr.score) filter (where mnl.channel_id = 5) as bbb_avg_score,
        --avg_yelp
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Palo Alto') as yelp_avg_score_palo_alto,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Jose') as yelp_avg_score_san_jose,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Oakland') as yelp_avg_score_oakland,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Francisco') as yelp_avg_score_san_francisco,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Sacramento') as yelp_avg_score_sacramento,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Napa' ) as yelp_avg_score_napa,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Watsonville') as yelp_avg_score_watsonville,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Fresno') as yelp_avg_score_fresno,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Stockton') as yelp_avg_score_stockton,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Riverside') as yelp_avg_score_riverside,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Lake Forest') as yelp_avg_score_lake_forest,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Thousand Oaks') as yelp_avg_score_thousand_oaks,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Los Angeles') as yelp_avg_score_los_angeles,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Diego') as yelp_avg_score_san_diego,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Dallas') as yelp_avg_score_dallas,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Fort Worth') as yelp_avg_score_fort_worth,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Houston') as yelp_avg_score_houston,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - San Antonio') as yelp_avg_score_san_antonio,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Austin') as yelp_avg_score_austin,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Atlanta') as yelp_avg_score_atlanta,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = '') as yelp_avg_score_no_locations,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Baltimore') as yelp_avg_score_baltimore,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Maryland DC') as yelp_avg_score_maryland_dc,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Philadelphia') as yelp_avg_score_philadelphia,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Arlington') as yelp_avg_score_arlington,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Miami') as yelp_avg_score_miami,
        avg(fr.score) filter (where fr.is_yelp_recommended is true and mnl.label = 'Yelp - Orlando') as yelp_avg_score_orlando,
        avg(fr.score) filter (where mnl.channel_id = 1 and fr.is_yelp_recommended is true and mnl.label = 'Yelp - Seattle') as yelp_avg_score_seattle
    from feedback_review fr
    left join marketing_localaccount mnl on mnl.id = fr.account_id
    left join store_order o on o.id = fr.order_id
    left join core_house h on h.id = o.house_id
    left join customers_customer cc on cc.id = h.customer_id
    left join geo_address ga on ga.id = h.address_id
    left join geo_county cn on cn.id = ga.county_id
    left join product_countymarket pcnm on pcnm.county_id = cn.id
    left join product_market pm on pm.id = pcnm.market_id
    left join positive_reviews pr on pr.review_id = fr.id
    where /*mnl.channel_id = 1 and*/ fr.deleted_at is null and ha_review_rank = 1
    group by 1
  )
select
    cs.day as date,
    date_trunc('{period}',cs.day)::date as day,
    coalesce(sum(yd.all_reviews) over (order by cs.day),0) as MAR1699,
    coalesce(sum(yd.all_reviews-yd.yelp_non_positive_reviews) over (order by cs.day),0) as MAR2221,
    coalesce(sum(yd.all_reviews_cn_eb) over (order by cs.day),0) as MAR1710,
    coalesce(sum(yd.all_reviews_cn_sa) over (order by cs.day),0) as MAR1717,
    coalesce(sum(yd.all_reviews_cn_sb) over (order by cs.day),0) as MAR1724,
    coalesce(sum(yd.all_reviews_cn_sj) over (order by cs.day),0) as MAR1731,
    coalesce(sum(yd.all_reviews_cn_pa) over (order by cs.day),0) as MAR1738,
    coalesce(sum(yd.all_reviews_cn_nb) over (order by cs.day),0) as MAR1745,
    coalesce(sum(yd.all_reviews_cn_sf) over (order by cs.day),0) as MAR1752,
    coalesce(sum(yd.all_reviews_cn_fr) over (order by cs.day),0) as MAR1759,
    coalesce(sum(yd.all_reviews_cn_st) over (order by cs.day),0) as MAR1766,
    coalesce(sum(yd.all_reviews_cn_wa) over (order by cs.day),0) as MAR1980,
    coalesce(sum(yd.all_reviews_cs_sv) over (order by cs.day),0) as MAR1773,
    coalesce(sum(yd.all_reviews_cs_oc) over (order by cs.day),0) as MAR1780,
    coalesce(sum(yd.all_reviews_cs_la) over (order by cs.day),0) as MAR1787,
    coalesce(sum(yd.all_reviews_cs_vc) over (order by cs.day),0) as MAR1794,
    coalesce(sum(yd.all_reviews_cs_sd) over (order by cs.day),0) as MAR1801,
    coalesce(sum(yd.all_reviews_tx_dl) over (order by cs.day),0) as MAR1808,
    coalesce(sum(yd.all_reviews_tx_sa) over (order by cs.day),0) as MAR1815,
    coalesce(sum(yd.all_reviews_tx_fw) over (order by cs.day),0) as MAR1822,
    coalesce(sum(yd.all_reviews_tx_ht) over (order by cs.day),0) as MAR1987,
    coalesce(sum(yd.all_reviews_tx_au) over (order by cs.day),0) as MAR1994,
    coalesce(sum(yd.all_reviews_ga_at) over (order by cs.day),0) as MAR1829,
    coalesce(sum(yd.all_reviews_md_bl) over (order by cs.day),0) as MAR1836,
    coalesce(sum(yd.all_reviews_md_dc) over (order by cs.day),0) as MAR1843,
    coalesce(sum(yd.all_reviews_pa_ph) over (order by cs.day),0) as MAR1850,
    coalesce(sum(yd.all_reviews_va_ar) over (order by cs.day),0) as MAR1857,
    coalesce(sum(yd.all_reviews_fl_mi) over (order by cs.day),0) as MAR1864,
    coalesce(sum(yd.all_reviews_fl_or) over (order by cs.day),0) as MAR2001,
    coalesce(sum(yd.all_reviews_yelp) over (order by cs.day),0) as MAR1871,
    coalesce(sum(yd.all_positive_reviews_yelp) over (order by cs.day),0) as MAR2211,
    coalesce(sum(yd.all_reviews_google) over (order by cs.day),0) as MAR1878,
    coalesce(sum(yd.all_positive_reviews_google) over (order by cs.day),0) as MAR2212,
    coalesce(sum(yd.all_reviews_ha) over (order by cs.day),0) as MAR1883,
    coalesce(sum(yd.all_positive_reviews_ha) over (order by cs.day),0) as MAR2213,
    coalesce(sum(yd.all_reviews_tt) over (order by cs.day),0) as MAR1888,
    coalesce(sum(yd.all_positive_reviews_tt) over (order by cs.day),0) as MAR2214,
    coalesce(sum(yd.all_reviews_bbb) over (order by cs.day),0) as MAR1893,
    coalesce(sum(yd.all_positive_reviews_bbb) over (order by cs.day),0) as MAR2215,
    coalesce(sum(yd.yelp_positive_reviews) over (order by cs.day),0) as MAR188,
    coalesce(sum(yd.yelp_non_positive_reviews) over (order by cs.day),0) as yelp_non_positive_reviews,
    coalesce(sum(yd.all_reviews_yelp) over (order by cs.day),0) as all_reviews_yelp,
    coalesce(sum(yd.yelp_positive_reviews_palo_alto) over (order by cs.day),0) as MAR284,
    coalesce(sum(yd.yelp_positive_reviews_houston) over (order by cs.day),0) as MAR1062,
    coalesce(sum(yd.yelp_positive_reviews_san_antonio) over (order by cs.day),0) as MAR1109,
    coalesce(sum(yd.yelp_positive_reviews_austin) over (order by cs.day),0) as MAR1103,
    coalesce(sum(yd.yelp_positive_reviews_atlanta) over (order by cs.day),0) as MAR1063,
    coalesce(sum(yd.yelp_positive_reviews_san_jose) over (order by cs.day), 0) as MAR290,
    coalesce(sum(yd.yelp_positive_reviews_oakland) over (order by cs.day), 0) as MAR288,
    coalesce(sum(yd.yelp_positive_reviews_san_francisco) over (order by cs.day), 0) as MAR343,
    coalesce(sum(yd.yelp_positive_reviews_sacramento) over (order by cs.day), 0) as MAR286,
    coalesce(sum(yd.yelp_positive_reviews_napa) over (order by cs.day), 0) as MAR291,
    coalesce(sum(yd.yelp_positive_reviews_watsonville) over (order by cs.day), 0) as MAR285,
    coalesce(sum(yd.yelp_positive_reviews_fresno) over (order by cs.day), 0) as MAR289,
    coalesce(sum(yd.yelp_positive_reviews_stockton) over (order by cs.day), 0) as MAR287,
    coalesce(sum(yd.yelp_positive_reviews_riverside) over (order by cs.day),0) as MAR574,
    coalesce(sum(yd.yelp_positive_reviews_lake_forest) over (order by cs.day),0) as MAR575,
    coalesce(sum(yd.yelp_positive_reviews_thousand_oaks) over (order by cs.day),0) as MAR576,
    coalesce(sum(yd.yelp_positive_reviews_los_angeles) over (order by cs.day),0) as MAR713,
    coalesce(sum(yd.yelp_positive_reviews_san_diego) over (order by cs.day),0) as MAR934,
    coalesce(sum(yd.yelp_positive_reviews_dallas) over (order by cs.day),0) as MAR935,
    coalesce(sum(yd.yelp_positive_reviews_fort_worth) over (order by cs.day),0) as MAR936,
    coalesce(sum(yd.all_reviews_yelp_palo_alto) over (order by cs.day),0) as all_reviews_yelp_paloalto,
    coalesce(sum(yd.all_reviews_yelp_san_jose) over (order by cs.day), 0) as all_reviews_yelp_san_jose,
    coalesce(sum(yd.all_reviews_yelp_oakland) over (order by cs.day), 0) as all_reviews_yelp_oakland,
    coalesce(sum(yd.all_reviews_yelp_san_francisco) over (order by cs.day), 0) as all_reviews_yelp_san_francisco,
    coalesce(sum(yd.all_reviews_yelp_sacramento) over (order by cs.day), 0) as all_reviews_yelp_sacramento,
    coalesce(sum(yd.all_reviews_yelp_napa) over (order by cs.day), 0) as all_reviews_yelp_napa,
    coalesce(sum(yd.all_reviews_yelp_watsonville) over (order by cs.day), 0) as all_reviews_yelp_watsonville,
    coalesce(sum(yd.all_reviews_yelp_fresno) over (order by cs.day), 0) as all_reviews_yelp_fresno,
    coalesce(sum(yd.all_reviews_yelp_stockton) over (order by cs.day), 0) as all_reviews_yelp_stockton,
    coalesce(sum(yd.all_reviews_yelp_riverside) over (order by cs.day),0) as all_reviews_yelp_riverside,
    coalesce(sum(yd.all_reviews_yelp_lake_forest) over (order by cs.day),0) as all_reviews_yelp_lake_forest,
    coalesce(sum(yd.all_reviews_yelp_thousand_oaks) over (order by cs.day),0) as all_reviews_yelp_thousand_oaks,
    coalesce(sum(yd.all_reviews_yelp_los_angeles) over (order by cs.day),0) as all_reviews_yelp_los_angeles,
    coalesce(sum(yd.all_reviews_yelp_san_diego) over (order by cs.day),0) as all_reviews_yelp_san_diego,
    coalesce(sum(yd.all_reviews_yelp_dallas) over (order by cs.day),0) as all_reviews_yelp_dallas,
    coalesce(sum(yd.all_reviews_yelp_fort_worth) over (order by cs.day),0) as all_reviews_yelp_fort_worth,
    coalesce(sum(yd.all_reviews_yelp_houston) over (order by cs.day),0) as all_reviews_yelp_houston,
    coalesce(sum(yd.all_reviews_yelp_san_antonio) over (order by cs.day),0) as all_reviews_yelp_san_antonio,
    coalesce(sum(yd.all_reviews_yelp_austin) over (order by cs.day),0) as all_reviews_yelp_austin,
    coalesce(sum(yd.all_reviews_yelp_atlanta) over (order by cs.day),0) as all_reviews_yelp_atlanta,
    coalesce(sum(yd.all_reviews_yelp_baltimore) over (order by cs.day), 0) as all_reviews_yelp_baltimore,
    coalesce(sum(yd.all_reviews_yelp_maryland_dc) over (order by cs.day), 0) as all_reviews_yelp_maryland_dc,
    coalesce(sum(yd.all_reviews_yelp_philadelphia) over (order by cs.day), 0) as all_reviews_yelp_philadelphia,
    coalesce(sum(yd.all_reviews_yelp_arlington) over (order by cs.day), 0) as all_reviews_yelp_arlington,
    coalesce(sum(yd.all_reviews_yelp_miami) over (order by cs.day), 0) as all_reviews_yelp_miami,
    coalesce(sum(yd.all_reviews_yelp_orlando) over (order by cs.day), 0) as all_reviews_yelp_orlando,
    coalesce(sum(yd.all_reviews_yelp_seattle) over (order by cs.day), 0) as all_reviews_yelp_seattle,
    coalesce(avg(yd.avg_score) over (order by cs.day),0) as MAR1706,
    coalesce(avg(yd.avg_score_cn_eb) over (order by cs.day),0) as MAR1713,
    coalesce(avg(yd.avg_score_cn_sa) over (order by cs.day),0) as MAR1720,
    coalesce(avg(yd.avg_score_cn_sb) over (order by cs.day),0) as MAR1727,
    coalesce(avg(yd.avg_score_cn_sj) over (order by cs.day),0) as MAR1734,
    coalesce(avg(yd.avg_score_cn_pa) over (order by cs.day),0) as MAR1741,
    coalesce(avg(yd.avg_score_cn_nb) over (order by cs.day),0) as MAR1748,
    coalesce(avg(yd.avg_score_cn_sf) over (order by cs.day),0) as MAR1755,
    coalesce(avg(yd.avg_score_cn_fr) over (order by cs.day),0) as MAR1762,
    coalesce(avg(yd.avg_score_cn_st) over (order by cs.day),0) as MAR1769,
    coalesce(avg(yd.avg_score_cn_wa) over (order by cs.day),0) as MAR1983,
    coalesce(avg(yd.avg_score_cs_sv) over (order by cs.day),0) as MAR1776,
    coalesce(avg(yd.avg_score_cs_oc) over (order by cs.day),0) as MAR1783,
    coalesce(avg(yd.avg_score_cs_la) over (order by cs.day),0) as MAR1790,
    coalesce(avg(yd.avg_score_cs_vc) over (order by cs.day),0) as MAR1797,
    coalesce(avg(yd.avg_score_cs_sd) over (order by cs.day),0) as MAR1804,
    coalesce(avg(yd.avg_score_tx_dl) over (order by cs.day),0) as MAR1811,
    coalesce(avg(yd.avg_score_tx_sa) over (order by cs.day),0) as MAR1818,
    coalesce(avg(yd.avg_score_tx_fw) over (order by cs.day),0) as MAR1825,
    coalesce(avg(yd.avg_score_tx_ht) over (order by cs.day),0) as MAR1990,
    coalesce(avg(yd.avg_score_tx_au) over (order by cs.day),0) as MAR1997,
    coalesce(avg(yd.avg_score_ga_at) over (order by cs.day),0) as MAR1832,
    coalesce(avg(yd.avg_score_md_bl) over (order by cs.day),0) as MAR1839,
    coalesce(avg(yd.avg_score_md_dc) over (order by cs.day),0) as MAR1846,
    coalesce(avg(yd.avg_score_pa_ph) over (order by cs.day),0) as MAR1853,
    coalesce(avg(yd.avg_score_va_ar) over (order by cs.day),0) as MAR1860,
    coalesce(avg(yd.avg_score_fl_mi) over (order by cs.day),0) as MAR1867,
    coalesce(avg(yd.avg_score_fl_or) over (order by cs.day),0) as MAR2004,
    coalesce(avg(yd.yelp_avg_score) over (order by cs.day),0) as MAR274,
    coalesce(avg(yd.google_avg_score) over (order by cs.day),0) as MAR1879,
    coalesce(avg(yd.ha_avg_score) over (order by cs.day),0) as MAR1884,
    coalesce(avg(yd.tt_avg_score) over (order by cs.day),0) as MAR1889,
    coalesce(avg(yd.bbb_avg_score) over (order by cs.day),0) as MAR1894,
    coalesce(avg(yd.yelp_avg_score_palo_alto) over (order by cs.day), 0) as MAR275,
    coalesce(avg(yd.yelp_avg_score_san_jose) over (order by cs.day), 0) as MAR281,
    coalesce(avg(yd.yelp_avg_score_oakland) over (order by cs.day), 0) as MAR279,
    coalesce(avg(yd.yelp_avg_score_san_francisco) over (order by cs.day), 0) as MAR342,
    coalesce(avg(yd.yelp_avg_score_sacramento) over (order by cs.day), 0) as MAR277,
    coalesce(avg(yd.yelp_avg_score_napa) over (order by cs.day), 0) as MAR282,
    coalesce(avg(yd.yelp_avg_score_watsonville) over (order by cs.day), 0) as MAR276,
    coalesce(avg(yd.yelp_avg_score_fresno) over (order by cs.day), 0) as MAR280,
    coalesce(avg(yd.yelp_avg_score_stockton) over (order by cs.day), 0) as MAR278,
    coalesce(avg(yd.yelp_avg_score_riverside) over (order by cs.day), 0) as MAR580,
    coalesce(avg(yd.yelp_avg_score_lake_forest) over (order by cs.day),0) as MAR581,
    coalesce(avg(yd.yelp_avg_score_thousand_oaks) over (order by cs.day),0) as MAR582,
    coalesce(avg(yd.yelp_avg_score_los_angeles) over (order by cs.day),0) as MAR712,
    coalesce(avg(yd.yelp_avg_score_san_diego) over (order by cs.day),0) as MAR928,
    coalesce(avg(yd.yelp_avg_score_dallas) over (order by cs.day),0) as MAR929,
    coalesce(avg(yd.yelp_avg_score_fort_worth) over (order by cs.day),0) as MAR930,
    coalesce(avg(yd.yelp_avg_score_houston) over (order by cs.day),0) as MAR1027,
    coalesce(avg(yd.yelp_avg_score_san_antonio) over (order by cs.day),0) as MAR1107,
    coalesce(avg(yd.yelp_avg_score_austin) over (order by cs.day),0) as MAR1108,
    coalesce(avg(yd.yelp_avg_score_atlanta) over (order by cs.day),0) as MAR1061,
    coalesce(avg(yd.yelp_avg_score_baltimore) over (order by cs.day), 0) as MAR1116,
    coalesce(avg(yd.yelp_avg_score_maryland_dc) over (order by cs.day), 0) as MAR1157,
    coalesce(avg(yd.yelp_avg_score_philadelphia) over (order by cs.day), 0) as MAR1223,
    coalesce(avg(yd.yelp_avg_score_arlington) over (order by cs.day), 0) as MAR1502,
    coalesce(avg(yd.yelp_avg_score_miami) over (order by cs.day), 0) as MAR1612,
    coalesce(avg(yd.yelp_avg_score_orlando) over (order by cs.day), 0) as MAR1660,
    coalesce(sum(yd.yelp_positive_reviews_baltimore) over (order by cs.day), 0) as MAR1117,
    coalesce(sum(yd.yelp_positive_reviews_maryland_dc) over (order by cs.day), 0) as MAR1158,
    coalesce(sum(yd.yelp_positive_reviews_philadelphia) over (order by cs.day), 0) as MAR1224,
    coalesce(sum(yd.yelp_positive_reviews_arlington) over (order by cs.day), 0) as MAR1503,
    coalesce(sum(yd.yelp_positive_reviews_miami) over (order by cs.day), 0) as MAR1613,
    coalesce(sum(yd.yelp_positive_reviews_orlando) over (order by cs.day), 0) as MAR1661,
    coalesce(avg(yd.yelp_avg_score_seattle) over (order by cs.day), 0) as MAR2228,
    coalesce(sum(yd.yelp_positive_reviews_seattle) over (order by cs.day), 0) as MAR2229
from calc_series cs
left join yelp_data yd on cs.day = yd.date_id
order by 1 desc
) as full_data
order by 1 desc
) as complete_data
where rank = '1'
