-- upload to BQ
with unique_ha_reviews as 
(
        select 
		fr.id as review_id,
		case when mnl.channel_id in (3,10) then row_number() over (partition by fr.order_id order by fr.posted_at) else 1 end as ha_review_rank
	from feedback_review fr
        left join marketing_localaccount mnl on mnl.id = fr.account_id 
)
select 
        date_trunc('{period}', fr.posted_at at time zone 'America/Los_Angeles')::date as date,
        count(*) as MAR1700,
        sum(case when pcnm.market_id = 2 then 1 else 0 end) as MAR1711,
        sum(case when pcnm.market_id = 3 then 1 else 0 end) as MAR1718,
        sum(case when pcnm.market_id in (4,30,31) then 1 else 0 end) as MAR1725,
        sum(case when pcnm.market_id = 30 then 1 else 0 end) as MAR1732,
        sum(case when pcnm.market_id = 31 then 1 else 0 end) as MAR1739,
        sum(case when pcnm.market_id = 9 then 1 else 0 end) as MAR1746,
        sum(case when pcnm.market_id = 8 then 1 else 0 end) as MAR1753,
        sum(case when pcnm.market_id = 10 then 1 else 0 end) as MAR1760,
        sum(case when pcnm.market_id = 29 then 1 else 0 end) as MAR1767,
        sum(case when pcnm.market_id = 4 then 1 else 0 end) as MAR1981,
        sum(case when pcnm.market_id = 14 then 1 else 0 end) as MAR1774,
        sum(case when pcnm.market_id = 5 then 1 else 0 end) as MAR1781,
        sum(case when pcnm.market_id = 6 then 1 else 0 end) as MAR1788,
        sum(case when pcnm.market_id = 7 then 1 else 0 end) as MAR1795,
        sum(case when pcnm.market_id = 1 then 1 else 0 end) as MAR1802,
        sum(case when pcnm.market_id = 16 then 1 else 0 end) as MAR1809,
        sum(case when pcnm.market_id = 19 then 1 else 0 end) as MAR1816,
        sum(case when pcnm.market_id = 17 then 1 else 0 end) as MAR1823,
        sum(case when pcnm.market_id = 18 then 1 else 0 end) as MAR1988,
        sum(case when pcnm.market_id = 32 then 1 else 0 end) as MAR1995,
        sum(case when pcnm.market_id = 20 then 1 else 0 end) as MAR1830,
        sum(case when pcnm.market_id = 22 then 1 else 0 end) as MAR1837,
        sum(case when pcnm.market_id = 21 then 1 else 0 end) as MAR1844,
        sum(case when pcnm.market_id = 33 then 1 else 0 end) as MAR1851,
        sum(case when pcnm.market_id = 35 then 1 else 0 end) as MAR1858,
        sum(case when pcnm.market_id = 24 then 1 else 0 end) as MAR1865,
        sum(case when pcnm.market_id = 26 then 1 else 0 end) as MAR2002,
        sum(case when pcnm.market_id = 42 then 1 else 0 end) as MAR2896,
        sum(case when pcnm.market_id = 57 then 1 else 0 end) as MAR2955,
        sum(case when pcnm.market_id = 58 then 1 else 0 end) as MAR3014,
        sum(case when mnl.channel_id = 1 then 1 else 0 end) as MAR301,
        sum(case when mnl.channel_id = 2 then 1 else 0 end) as MAR1880,
        sum(case when mnl.channel_id in (3,10) then 1 else 0 end) as MAR1885,
        sum(case when mnl.channel_id = 4 then 1 else 0 end) as MAR1890,
        sum(case when mnl.channel_id = 5 then 1 else 0 end) as MAR1895,
        count(fr.id) filter (where fr.score >= 4) as MAR1956,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 2) as MAR1957,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 3) as MAR1958,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id in (4,30,31)) as MAR1959,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 30) as MAR1960,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 31) as MAR1961,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 9) as MAR1962,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 8) as MAR1963,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 10) as MAR1964,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 29) as MAR1965,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 4) as MAR2016,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 14) as MAR1966,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 5) as MAR1967,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 6) as MAR1968,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 7) as MAR1969,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 1) as MAR1970,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 16) as MAR1971,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 19) as MAR1972,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 17) as MAR1973,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 18) as MAR2017,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 32) as MAR2018,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 20) as MAR1974,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 22) as MAR1975,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 21) as MAR1976,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 33) as MAR1977,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 35) as MAR1978,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 24) as MAR1979,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 26) as MAR2019,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 42) as MAR2904,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 57) as MAR2963,
        count(fr.id) filter (where fr.score >= 4 and pcnm.market_id = 58) as MAR3022,
        sum(case when fr.sales_staff_attributed_id is not null then 1 else 0 end) as MAR1898,
        sum(case when fr.delivery_staff_attributed_id is not null then 1 else 0 end) as MAR1899,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 2 then 1 else 0 end) as MAR1900,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 2 then 1 else 0 end) as MAR1901,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 3 then 1 else 0 end) as MAR1902,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 3 then 1 else 0 end) as MAR1903,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id in (4,30,31) then 1 else 0 end) as MAR1904,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id in (4,30,31) then 1 else 0 end) as MAR1905,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 30 then 1 else 0 end) as MAR1906,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 30 then 1 else 0 end) as MAR1907,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 31 then 1 else 0 end) as MAR1908,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 31 then 1 else 0 end) as MAR1909,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 9 then 1 else 0 end) as MAR1910,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 9 then 1 else 0 end) as MAR1911,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 8 then 1 else 0 end) as MAR1912,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 8 then 1 else 0 end) as MAR1913,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 10 then 1 else 0 end) as MAR1914,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 10 then 1 else 0 end) as MAR1915,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 29 then 1 else 0 end) as MAR1916,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 29 then 1 else 0 end) as MAR1917,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 4 then 1 else 0 end) as MAR2008,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 4 then 1 else 0 end) as MAR2009,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 14 then 1 else 0 end) as MAR1918,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 14 then 1 else 0 end) as MAR1919,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 5 then 1 else 0 end) as MAR1920,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 5 then 1 else 0 end) as MAR1921,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 6 then 1 else 0 end) as MAR1922,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 6 then 1 else 0 end) as MAR1923,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 7 then 1 else 0 end) as MAR1924,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 7 then 1 else 0 end) as MAR1925,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 1 then 1 else 0 end) as MAR1926,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 1 then 1 else 0 end) as MAR1927,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 16 then 1 else 0 end) as MAR1928,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 16 then 1 else 0 end) as MAR1929,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 19 then 1 else 0 end) as MAR1930,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 19 then 1 else 0 end) as MAR1931,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 17 then 1 else 0 end) as MAR1932,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 17 then 1 else 0 end) as MAR1933,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 18 then 1 else 0 end) as MAR2010,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 18 then 1 else 0 end) as MAR2011,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 32 then 1 else 0 end) as MAR2012,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 32 then 1 else 0 end) as MAR2013,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 20 then 1 else 0 end) as MAR1934,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 20 then 1 else 0 end) as MAR1935,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 22 then 1 else 0 end) as MAR1936,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 22 then 1 else 0 end) as MAR1937,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 21 then 1 else 0 end) as MAR1938,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 21 then 1 else 0 end) as MAR1939,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 33 then 1 else 0 end) as MAR1940,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 33 then 1 else 0 end) as MAR1941,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 35 then 1 else 0 end) as MAR1942,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 35 then 1 else 0 end) as MAR1943,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 24 then 1 else 0 end) as MAR1944,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 24 then 1 else 0 end) as MAR1945,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 26 then 1 else 0 end) as MAR2014,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 26 then 1 else 0 end) as MAR2015,
        sum(case when fr.sales_staff_attributed_id is not null and mnl.channel_id = 1 then 1 else 0 end) as MAR731,
        sum(case when fr.delivery_staff_attributed_id is not null and mnl.channel_id = 1 is not null then 1 else 0 end) as MAR732,
        sum(case when fr.sales_staff_attributed_id is not null and mnl.channel_id = 2 then 1 else 0 end) as MAR1948,
        sum(case when fr.delivery_staff_attributed_id is not null and mnl.channel_id = 2 is not null then 1 else 0 end) as MAR1949,
        sum(case when fr.sales_staff_attributed_id is not null and mnl.channel_id in (3,10) then 1 else 0 end) as MAR1950,
        sum(case when fr.delivery_staff_attributed_id is not null and mnl.channel_id in (3,10) is not null then 1 else 0 end) as MAR1951,
        sum(case when fr.sales_staff_attributed_id is not null and mnl.channel_id = 4 then 1 else 0 end) as MAR1952,
        sum(case when fr.delivery_staff_attributed_id is not null and mnl.channel_id = 4 is not null then 1 else 0 end) as MAR1953,
        sum(case when fr.sales_staff_attributed_id is not null and mnl.channel_id = 5 then 1 else 0 end) as MAR1954,
        sum(case when fr.delivery_staff_attributed_id is not null and mnl.channel_id = 5 is not null then 1 else 0 end) as MAR1955,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 42 then 1 else 0 end) as MAR2902,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 42 then 1 else 0 end) as MAR1903,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 57 then 1 else 0 end) as MAR2961,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 57 then 1 else 0 end) as MAR2962,
        sum(case when fr.sales_staff_attributed_id is not null and pcnm.market_id = 58 then 1 else 0 end) as MAR3020,
        sum(case when fr.delivery_staff_attributed_id is not null and pcnm.market_id = 58 then 1 else 0 end) as MAR3021,
        sum(case when mnl.label = 'Yelp - Palo Alto' then 1 else 0 end) as MAR513,
        sum(case when mnl.label = 'Yelp - San Jose' then 1 else 0 end) as MAR514,
        sum(case when mnl.label = 'Yelp - Oakland' then 1 else 0 end) as MAR515,
        sum(case when mnl.label = 'Yelp - San Francisco' then 1 else 0 end) as MAR516,
        sum(case when mnl.label = 'Yelp - Sacramento' then 1 else 0 end) as MAR517,
        sum(case when mnl.label = 'Yelp - Napa' then 1 else 0 end) as MAR518,
        sum(case when mnl.label = 'Yelp - Watsonville' then 1 else 0 end) as MAR519,
        sum(case when mnl.label = 'Yelp - Fresno' then 1 else 0 end) as MAR520,
        sum(case when mnl.label = 'Yelp - Stockton' then 1 else 0 end) as MAR521,
        sum(case when mnl.label = 'Yelp - Riverside' then 1 else 0 end) as MAR522,
        sum(case when mnl.label = 'Yelp - Lake Forest' then 1 else 0 end) as MAR523,
        sum(case when mnl.label = 'Yelp - Thousand Oaks' then 1 else 0 end) as MAR524,
        sum(case when mnl.label = 'Yelp - Los Angeles' then 1 else 0 end) as MAR710,
        sum(case when mnl.label = 'Yelp - San Diego' then 1 else 0 end) as MAR937,
        sum(case when mnl.label = 'Yelp - Dallas' then 1 else 0 end) as MAR938,
        sum(case when mnl.label = 'Yelp - Fort Worth' then 1 else 0 end) as MAR939,
        sum(case when mnl.label = 'Yelp - Houston' then 1 else 0 end) as MAR1066,
        sum(case when mnl.label = 'Yelp - San Antonio' then 1 else 0 end) as MAR1111,
        sum(case when mnl.label = 'Yelp - Austin' then 1 else 0 end) as MAR1105,
        sum(case when mnl.label = 'Yelp - Atlanta' then 1 else 0 end) as MAR1067,
        sum(case when mnl.label = 'Yelp - Baltimore' then 1 else 0 end) as MAR1120,
        sum(case when mnl.label = 'Yelp - Maryland DC' then 1 else 0 end) as MAR1161,
        sum(case when mnl.label = 'Yelp - Arlington' then 1 else 0 end) as MAR1531,
        sum(case when mnl.label = 'Yelp - Miami' then 1 else 0 end) as MAR1641,
        sum(case when mnl.label = 'Yelp - Orlando' then 1 else 0 end) as MAR1689,
        sum(case when mnl.label = 'Yelp - Philadelphia' then 1 else 0 end) as MAR1252,
        sum(case when mnl.label = 'Yelp - Seatle' then 1 else 0 end) as MAR2258,
        coalesce(avg(fr.score),0) as MAR525,
        coalesce(avg(case when fr.sales_staff_attributed_id is not null and mnl.channel_id = 1 then fr.score else null end),0) as MAR733,
        coalesce(avg(case when fr.delivery_staff_attributed_id is not null and mnl.channel_id = 1 then fr.score else null end),0) as MAR734,
        coalesce(avg(case when fr.sales_staff_attributed_id is not null then fr.score else null end),0) as MAR2223,
        coalesce(avg(case when fr.delivery_staff_attributed_id is not null then fr.score else null end),0) as MAR2224,
        coalesce(avg(case when mnl.label = 'Yelp - Palo Alto' then fr.score else null end),0) as MAR526,
        coalesce(avg(case when mnl.label = 'Yelp - San Jose' then fr.score else null end),0) as MAR527,
        coalesce(avg(case when mnl.label = 'Yelp - Oakland' then fr.score else null end),0) as MAR528,
        coalesce(avg(case when mnl.label = 'Yelp - San Francisco' then fr.score else null end),0) as MAR529,
        coalesce(avg(case when mnl.label = 'Yelp - Sacramento' then fr.score else null end),0) as MAR530,
        coalesce(avg(case when mnl.label = 'Yelp - Napa' then fr.score else null end),0) as MAR531,
        coalesce(avg(case when mnl.label = 'Yelp - Watsonville' then fr.score else null end),0) as MAR532,
        coalesce(avg(case when mnl.label = 'Yelp - Fresno' then fr.score else null end),0) as MAR533,
        coalesce(avg(case when mnl.label = 'Yelp - Stockton' then fr.score else null end),0) as MAR534,
        coalesce(avg(case when mnl.label = 'Yelp - Riverside' then fr.score else null end),0) as MAR535,
        coalesce(avg(case when mnl.label = 'Yelp - Lake Forest' then fr.score else null end),0) as MAR536,
        coalesce(avg(case when mnl.label = 'Yelp - Thousand Oaks' then fr.score else null end),0) as MAR537,
        coalesce(avg(case when mnl.label = 'Yelp - Los Angeles' then fr.score else null end),0) as MAR711,
        coalesce(avg(case when mnl.label = 'Yelp - San Diego' then fr.score else null end),0) as MAR940,
        coalesce(avg(case when mnl.label = 'Yelp - Dallas' then fr.score else null end),0) as MAR941,
        coalesce(avg(case when mnl.label = 'Yelp - Fort Worth' then fr.score else null end),0) as MAR942,
        coalesce(avg(case when mnl.label = 'Yelp - Houston' then fr.score else null end),0) as MAR1068,
        coalesce(avg(case when mnl.label = 'Yelp - San Antonio' then fr.score else null end),0) as MAR1112,
        coalesce(avg(case when mnl.label = 'Yelp - Austin' then fr.score else null end),0) as MAR1106,
        coalesce(avg(case when mnl.label = 'Yelp - Atlanta' then fr.score else null end),0) as MAR1069,
        coalesce(avg(case when mnl.label = 'Yelp - Baltimore' then fr.score else null end),0) as MAR1122,
        coalesce(avg(case when mnl.label = 'Yelp - Maryland DC' then fr.score else null end),0) as MAR1163,
        coalesce(avg(case when mnl.label = 'Yelp - Arlington' then fr.score else null end),0) as MAR1532,
        coalesce(avg(case when mnl.label = 'Yelp - Miami' then fr.score else null end),0) as MAR1642,
        coalesce(avg(case when mnl.label = 'Yelp - Orlando' then fr.score else null end),0) as MAR1690,
        coalesce(avg(case when mnl.label = 'Yelp - Philadelphia' then fr.score else null end),0) as MAR1253,
        coalesce(avg(case when mnl.label = 'Yelp - Seatle' then fr.score else null end),0) as MAR2259
from feedback_review fr
left join marketing_localaccount mnl on mnl.id = fr.account_id
left join store_order o on o.id = fr.order_id
left join core_house h on h.id = o.house_id
left join customers_customer cc on cc.id = h.customer_id
left join geo_address ga on ga.id = h.address_id
left join geo_county cn on cn.id = ga.county_id
left join product_countymarket pcnm on pcnm.county_id = cn.id
left join product_market pm on pm.id = pcnm.market_id
left join unique_ha_reviews uha on uha.review_id = fr.id
where fr.posted_at at time zone 'America/Los_Angeles' >= '2018-04-16'
        and fr.order_id is not null
        and ha_review_rank = 1
/*and mnl.channel_id = 1*/
group by 1
