-- upload to BQ
select 
        date_trunc('{period}', fr.posted_at at time zone 'PDT')::date as date,
        count(*) as MAR301,
        sum(case when fr.sales_staff_attributed_id is not null then 1 else 0 end) as MAR731,
        sum(case when fr.delivery_staff_attributed_id is not null then 1 else 0 end) as MAR732,
        sum(case when mnl.label = 'Yelp - Palo Alto' then 1 else 0 end) as MAR513,
        sum(case when mnl.label = 'Yelp - San Jose' then 1 else 0 end) as MAR514,
        sum(case when mnl.label = 'Yelp - Oakland' then 1 else 0 end) as MAR515,
        sum(case when mnl.label = 'Yelp - San Francisco' then 1 else 0 end) as MAR516,
        sum(case when mnl.label = 'Yelp - Sacramento' then 1 else 0 end) as MAR517,
        sum(case when mnl.label = 'Yelp - Napa' then 1 else 0 end) as MAR518,
        sum(case when mnl.label = 'Yelp - Watsonville' then 1 else 0 end) as MAR519,
        sum(case when mnl.label = 'Yelp - Fresno' then 1 else 0 end) as MAR520,
        sum(case when mnl.label = 'Yelp - Stockton' then 1 else 0 end) as MAR521,
        sum(case when mnl.label = 'Yelp - Riverside' then 1 else 0 end) as MAR522,
        sum(case when mnl.label = 'Yelp - Lake Forest' then 1 else 0 end) as MAR523,
        sum(case when mnl.label = 'Yelp - Thousand Oaks' then 1 else 0 end) as MAR524,
        sum(case when mnl.label = 'Yelp - Los Angeles' then 1 else 0 end) as MAR710,
        sum(case when mnl.label = 'Yelp - San Diego' then 1 else 0 end) as MAR937,
        sum(case when mnl.label = 'Yelp - Dallas' then 1 else 0 end) as MAR938,
        sum(case when mnl.label = 'Yelp - Fort Worth' then 1 else 0 end) as MAR939,
        sum(case when mnl.label = 'Yelp - Houston' then 1 else 0 end) as MAR1066,
        sum(case when mnl.label = 'Yelp - San Antonio' then 1 else 0 end) as MAR1111,
        sum(case when mnl.label = 'Yelp - Austin' then 1 else 0 end) as MAR1105,
        sum(case when mnl.label = 'Yelp - Atlanta' then 1 else 0 end) as MAR1067,
        sum(case when mnl.label = 'Yelp - Baltimore' then 1 else 0 end) as MAR1120,
        sum(case when mnl.label = 'Yelp - Maryland DC' then 1 else 0 end) as MAR1161,
        coalesce(avg(fr.score),0) as MAR525,
        coalesce(avg(case when fr.sales_staff_attributed_id is not null then fr.score else null end),0) as MAR733,
        coalesce(avg(case when fr.delivery_staff_attributed_id is not null then fr.score else null end),0) as MAR734,
        coalesce(avg(case when mnl.label = 'Yelp - Palo Alto' then fr.score else null end),0) as MAR526,
        coalesce(avg(case when mnl.label = 'Yelp - San Jose' then fr.score else null end),0) as MAR527,
        coalesce(avg(case when mnl.label = 'Yelp - Oakland' then fr.score else null end),0) as MAR528,
        coalesce(avg(case when mnl.label = 'Yelp - San Francisco' then fr.score else null end),0) as MAR529,
        coalesce(avg(case when mnl.label = 'Yelp - Sacramento' then fr.score else null end),0) as MAR530,
        coalesce(avg(case when mnl.label = 'Yelp - Napa' then fr.score else null end),0) as MAR531,
        coalesce(avg(case when mnl.label = 'Yelp - Watsonville' then fr.score else null end),0) as MAR532,
        coalesce(avg(case when mnl.label = 'Yelp - Fresno' then fr.score else null end),0) as MAR533,
        coalesce(avg(case when mnl.label = 'Yelp - Stockton' then fr.score else null end),0) as MAR534,
        coalesce(avg(case when mnl.label = 'Yelp - Riverside' then fr.score else null end),0) as MAR535,
        coalesce(avg(case when mnl.label = 'Yelp - Lake Forest' then fr.score else null end),0) as MAR536,
        coalesce(avg(case when mnl.label = 'Yelp - Thousand Oaks' then fr.score else null end),0) as MAR537,
        coalesce(avg(case when mnl.label = 'Yelp - Los Angeles' then fr.score else null end),0) as MAR711,
        coalesce(avg(case when mnl.label = 'Yelp - San Diego' then fr.score else null end),0) as MAR940,
        coalesce(avg(case when mnl.label = 'Yelp - Dallas' then fr.score else null end),0) as MAR941,
        coalesce(avg(case when mnl.label = 'Yelp - Fort Worth' then fr.score else null end),0) as MAR942,
        coalesce(avg(case when mnl.label = 'Yelp - Houston' then fr.score else null end),0) as MAR1068,
        coalesce(avg(case when mnl.label = 'Yelp - San Antonio' then fr.score else null end),0) as MAR1112,
        coalesce(avg(case when mnl.label = 'Yelp - Austin' then fr.score else null end),0) as MAR1106,
        coalesce(avg(case when mnl.label = 'Yelp - Atlanta' then fr.score else null end),0) as MAR1069,
        coalesce(avg(case when mnl.label = 'Yelp - Baltimore' then fr.score else null end),0) as MAR1122,
        coalesce(avg(case when mnl.label = 'Yelp - Maryland DC' then fr.score else null end),0) as MAR1163
from feedback_review fr
left join marketing_localaccount mnl on mnl.id = fr.account_id
where date_trunc('quarter', fr.posted_at at time zone 'PDT')::date >= '2018-04-15'
and mnl.channel_id = 1
group by 1
order by 1
